## Send fetch main
GET http://localhost:3000/
### Send fetch songs request
GET http://localhost:3000/songs/?page=1&limit=10

### Send fetch song details request
GET http://localhost:3000/songs/1

### Send add song request
POST http://localhost:3000/songs
Content-Type: application/json

{
  "title": "Lasting lover 3",
  "artists": ["momo"],
  "releasedDate": "2022-01-01",
  "duration": "03:42",
  "lyrics": "momo2"
}

### Send delete song request
DELETE http://localhost:3000/songs/3

### Send update song request
PUT http://localhost:3000/songs/5
Content-Type: application/json

{
  "title": "Lasting lover 1",
  "artists": ["momo"],
  "releasedDate": "2022-01-04",
  "duration": "03:42",
  "lyrics": "momo"
}