## Send fetch main
GET http://localhost:3000/

### send get playlists
GET http://localhost:3000/playlists?page=1&limit=10

### create new Playlist
POST http://localhost:3000/playlists
Content-Type: application/json

{
  "name": "New Playlist 3",
  "songs": [
    7
  ],
  "user": 2
}
