### Send fetch songs request
GET http://localhost:3000/songs/?page=1&limit=10

### Send fetch song details request
GET http://localhost:3000/songs/1

### Send add song request
POST http://localhost:3000/songs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdlbkBleGFtcGxlLmNvbSIsInVzZXJJZCI6MiwiYXJ0aXN0SWQiOjEsImlhdCI6MTcyNDc3MTgzNCwiZXhwIjoxNzI0ODU4MjM0fQ.brkVQC5wF9Wu1UUpoPWuiB8D_N_nhQ1QK5U8sYk-7KU

{
  "title": "Animals",
  "artists": [1],
  "releasedDate": "2022-01-06",
  "duration": "03:42",
  "lyrics": "momo2"
}

### Send delete song request
DELETE http://localhost:3000/songs/5

### Send update song request
PUT http://localhost:3000/songs/5
Content-Type: application/json

{
  "title": "Lasting lover 1",
  "artists": ["momo"],
  "releasedDate": "2022-01-04",
  "duration": "03:42",
  "lyrics": "momo"
}
