### Signup
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "firstName": "Martin",
    "lastName": "Gen",
    "username": "martingen",
    "email": "martingen@example.com",
    "password": "123456"
}


### Login
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "martingen@example.com",
    "password": "123456"
}

### Profile
GET http://localhost:3000/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1hcnRpbmdlbkBleGFtcGxlLmNvbSIsInVzZXJJZCI6MiwiYXJ0aXN0SWQiOjEsImlhdCI6MTcyNDc3MTgzNCwiZXhwIjoxNzI0ODU4MjM0fQ.brkVQC5wF9Wu1UUpoPWuiB8D_N_nhQ1QK5U8sYk-7KU
